export const ADD_NEW_MOBILE_IN_REDUX = "ADD_NEW_MOBILE_IN_REDUX";
export const SET_EXISTING_MOBILE_IN_REDUX_FOR_UPDATING =
  "SET_EXISTING_MOBILE_IN_REDUX_FOR_UPDATING";
export const UPDATE_EXISTING_MOBILE_IN_REDUX =
  "UPDATE_EXISTING_MOBILE_IN_REDUX";
export const DELETE_EXISTING_MOBILE_BY_ID_FROM_REDUX =
  "DELETE_EXISTING_MOBILE_BY_ID_FROM_REDUX";
